from setuptools import find_packages, setup

setup(
    name="experiment_utils",
    version="0.1.0",
    packages=find_packages(include=["experiment_utils", "experiment_utils.*"]),
    author="Ahmed Younes",
    author_email="ahmed.younes.sam@gmail.com",
    description="A utility package for experiment management.",
    install_requires=[
        'aiohttp==3.9.5',
        'aiosignal==1.3.1',
        'appnope==0.1.4',
        'arabert==1.0.1',
        'asttokens==2.4.1',
        'async-timeout==4.0.3',
        'attrs==23.2.0',
        'black==24.4.2',
        'certifi==2022.12.7',
        'charset-normalizer==3.0.1',
        'click==8.1.7',
        'comm==0.2.2',
        'datasets==2.19.1',
        'debugpy==1.8.1',
        'decorator==5.1.1',
        'dill==0.3.8',
        'emoji==1.4.2',
        'exceptiongroup==1.2.1',
        'executing==2.0.1',
        'Farasa==0.0.1',
        'farasapy==0.0.14',
        'filelock==3.9.0',
        'frozenlist==1.4.1',
        'fsspec==2024.3.1',
        'huggingface-hub==0.21.2',
        'idna==3.4',
        'importlib-metadata==6.0.0',
        'iniconfig==2.0.0',
        'ipykernel==6.29.4',
        'ipython==8.18.1',
        'ipywidgets==8.1.3',
        'isort==5.13.2',
        'jedi==0.19.1',
        'joblib==1.2.0',
        'jupyter_client==8.6.2',
        'jupyter_core==5.7.2',
        'jupyterlab_widgets==3.0.11',
        'llvmlite==0.39.1',
        'matplotlib-inline==0.1.7',
        'multidict==6.0.5',
        'multiprocess==0.70.16',
        'mypy-extensions==1.0.0',
        'nest-asyncio==1.6.0',
        'numba==0.56.4',
        'numpy==1.23.5',
        'packaging==23.0',
        'pandas==1.5.3',
        'parso==0.8.4',
        'pathspec==0.12.1',
        'pexpect==4.9.0',
        'platformdirs==4.2.2',
        'plotly==5.14.1',
        'pluggy==1.5.0',
        'prompt_toolkit==3.0.45',
        'psutil==5.9.8',
        'ptyprocess==0.7.0',
        'pure-eval==0.2.2',
        'PyArabic==0.6.15',
        'pyarrow==16.1.0',
        'pyarrow-hotfix==0.6',
        'Pygments==2.18.0',
        'pynndescent==0.5.8',
        'pytest==8.2.1',
        'python-dateutil==2.8.2',
        'pytz==2022.7.1',
        'PyYAML==6.0',
        'pyzmq==26.0.3',
        'regex==2022.10.31',
        'requests==2.28.2',
        'scikit-learn==1.2.1',
        'scipy==1.10.0',
        'seqeval==1.2.2',
        'six==1.16.0',
        'stack-data==0.6.3',
        'tenacity==8.2.2',
        'threadpoolctl==3.1.0',
        'tokenizers==0.13.2',
        'tomli==2.0.1',
        'torch==1.13.1',
        'tornado==6.4',
        'tqdm==4.64.1',
        'traitlets==5.14.3',
        'transformers==4.26.0',
        'typing_extensions==4.4.0',
        'umap-learn==0.5.3',
        'urllib3==1.26.14',
        'wcwidth==0.2.13',
        'widgetsnbextension==4.0.11',
        'xxhash==3.4.1',
        'yarl==1.9.4',
        'zipp==3.15.0'
    ],
    # install_requires=[
    #     'appnope',
    #     'arabert',
    #     'asttokens',
    #     'certifi',
    #     'charset-normalizer',
    #     'comm',
    #     'debugpy',
    #     'decorator',
    #     'emoji',
    #     'exceptiongroup',
    #     'executing',
    #     'Farasa',
    #     'farasapy',
    #     'filelock',
    #     'huggingface-hub>=0.21.2',
    #     'idna',
    #     'importlib-metadata',
    #     'ipykernel',
    #     'ipython',
    #     'jedi',
    #     'joblib',
    #     'jupyter_client',
    #     'jupyter_core',
    #     'llvmlite',
    #     'matplotlib-inline',
    #     'nest-asyncio',
    #     'numba',
    #     'numpy',
    #     'packaging',
    #     'pandas',
    #     'parso',
    #     'pexpect',
    #     'platformdirs',
    #     'plotly',
    #     'prompt_toolkit',
    #     'psutil',
    #     'ptyprocess',
    #     'pure-eval',
    #     'PyArabic',
    #     'Pygments',
    #     'pynndescent',
    #     'python-dateutil',
    #     'pytz',
    #     'PyYAML',
    #     'pyzmq',
    #     'regex',
    #     'requests',
    #     'scikit-learn',
    #     'scipy',
    #     'seqeval',
    #     'six',
    #     'stack-data',
    #     'tenacity',
    #     'threadpoolctl',
    #     'tokenizers',
    #     'torch',
    #     'tornado',
    #     'tqdm',
    #     'traitlets',
    #     'transformers',
    #     'typing_extensions',
    #     'umap-learn',
    #     'urllib3',
    #     'wcwidth',
    #     'zipp',
    #     'ipywidgets',
    #     'pytest',
    #     'datasets'
    # ],
)
