from setuptools import find_packages, setup

setup(
    name="experiment_utils",
    version="0.1.0",
    packages=find_packages(include=["experiment_utils", "experiment_utils.*"]),
    author="Ahmed Younes",
    author_email="ahmed.younes.sam@gmail.com",
    description="A utility package for experiment management.",
    install_requires=[
        'appnope',
        'arabert',
        'asttokens',
        'certifi',
        'charset-normalizer',
        'comm',
        'debugpy',
        'decorator',
        'emoji',
        'exceptiongroup',
        'executing',
        'Farasa',
        'farasapy',
        'filelock',
        'huggingface-hub>=0.21.2',
        'idna',
        'importlib-metadata',
        'ipykernel',
        'ipython',
        'jedi',
        'joblib',
        'jupyter_client',
        'jupyter_core',
        'llvmlite',
        'matplotlib-inline',
        'nest-asyncio',
        'numba',
        # 'numpy==1.23.5',
        'numpy',
        'packaging',
        # 'pandas==1.5.3',
        'pandas',
        'parso',
        'pexpect',
        'platformdirs',
        'plotly',
        'prompt_toolkit',
        'psutil',
        'ptyprocess',
        'pure-eval',
        'PyArabic',
        'Pygments',
        'pynndescent',
        'python-dateutil',
        'pytz',
        'PyYAML',
        'pyzmq',
        'regex',
        'requests',
        'scikit-learn',
        'scipy',
        'seqeval',
        'six',
        'stack-data',
        'tenacity',
        'threadpoolctl',
        'tokenizers',
        'torch',
        'tornado',
        'tqdm',
        'traitlets',
        # 'transformers==4.26.0',
        'transformers',
        'typing_extensions',
        'umap-learn',
        'urllib3',
        'wcwidth',
        'zipp',
        'ipywidgets',
        'pytest',
        'datasets'
    ],
)
