from setuptools import find_packages, setup

with open('requirements.txt') as f:
    required = f.read().splitlines()

setup(
    name="experiment_utils",
    version="0.1.0",
    packages=find_packages(include=["experiment_utils", "experiment_utils.*"]),
    author="Ahmed Younes",
    author_email="ahmed.younes.sam@gmail.com",
    description="A utility package for experiment management.",
    install_requires=required
    # [
    #     'appnope==0.1.4',
    #     'arabert==1.0.1',
    #     'asttokens==2.4.1',
    #     'certifi==2022.12.7',
    #     'charset-normalizer==3.0.1',
    #     'comm==0.2.2',
    #     'debugpy==1.8.1',
    #     'decorator==5.1.1',
    #     'emoji==1.4.2',
    #     'exceptiongroup==1.2.1',
    #     'executing==2.0.1',
    #     'Farasa==0.0.1',
    #     'farasapy==0.0.14',
    #     'filelock==3.9.0',
    #     'huggingface-hub==0.12.0',
    #     'idna==3.4',
    #     'importlib-metadata==6.0.0',
    #     'ipykernel==6.29.4',
    #     'ipython==8.18.1',
    #     'jedi==0.19.1',
    #     'joblib==1.2.0',
    #     'jupyter_client==8.6.2',
    #     'jupyter_core==5.7.2',
    #     'llvmlite==0.39.1',
    #     'matplotlib-inline==0.1.7',
    #     'nest-asyncio==1.6.0',
    #     'numba==0.56.4',
    #     'numpy==1.23.5',
    #     'packaging==23.0',
    #     'pandas==1.5.3',
    #     'parso==0.8.4',
    #     'pexpect==4.9.0',
    #     'platformdirs==4.2.2',
    #     'plotly==5.14.1',
    #     'prompt_toolkit==3.0.45',
    #     'psutil==5.9.8',
    #     'ptyprocess==0.7.0',
    #     'pure-eval==0.2.2',
    #     'PyArabic==0.6.15',
    #     'Pygments==2.18.0',
    #     'pynndescent==0.5.8',
    #     'python-dateutil==2.8.2',
    #     'pytz==2022.7.1',
    #     'PyYAML==6.0',
    #     'pyzmq==26.0.3',
    #     'regex==2022.10.31',
    #     'requests==2.28.2',
    #     'scikit-learn==1.2.1',
    #     'scipy==1.10.0',
    #     'seqeval==1.2.2',
    #     'six==1.16.0',
    #     'stack-data==0.6.3',
    #     'tenacity==8.2.2',
    #     'threadpoolctl==3.1.0',
    #     'tokenizers==0.13.2',
    #     'torch==1.13.1',
    #     'tornado==6.4',
    #     'tqdm==4.64.1',
    #     'traitlets==5.14.3',
    #     'transformers==4.26.0',
    #     'typing_extensions==4.4.0',
    #     'umap-learn==0.5.3',
    #     'urllib3==1.26.14',
    #     'wcwidth==0.2.13',
    #     'zipp==3.15.0',
    #     'ipywidgets==8.1.3',
    #     'pytest==8.2.1'
    # ],
)
