ANERCorp_CamelLab:
  path: "ANERcorp-CamelLabSplits/ANERCorp_CamelLab"
  strategy: file
  splits:
    - "train"
    - "test"
    
ANERCorp_CamelLab-validation:
  path: "ANERcorp-CamelLabSplits/ANERCorp_CamelLab"
  strategy: file
  splits:
    - "train"
    - "test"
  validation_size: 0.2

conll2003:
  dataset_name: "conll2003"
  strategy: dataset
  splits:
    - "train"
    - "validation"
    - "test"
